# RaLP Configuration
settings:
  # Available languages: en_us, ru_ru, de_de, es_es, pt_pt, fr_fr, tr_tr, it_it, ko_kr, ja_jp, zh_cn, pl_pl
  default-language: en_us
  min-password-length: 3
  max-login-attempts: 3
  block-time: 60
  enable-auto-login: true
  auto-login-ip-check: true
  session-duration: 5
  sound:
    enabled: true
    name: "entity.ghast.ambient"
    volume: 1.0
    pitch: 1.0
auto-login: {}